[package]
name = "fuck-rust-day-by-day"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1", features = ["full"]}
tokio-util = {version = "0.7", features = ["codec"]}
bytes = "1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
