[package]
name = "hello-axum"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = {version = "1", features = ["full"]}
serde = { version = "1", features = ["derive"] } # 加上 serde
serde_json = "1"
